FROM centos:7

MAINTAINER Arvind Nadendla <arvindn05@gmail.com>

ENV http_proxy http://proxy-chain.intel.com:911
ENV https_proxy https://proxy-chain.intel.com:912

RUN yum update -y && \
yum install -y wget && \
wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u161-b12/0da788060d494f5095bf8624735fa2f1/jre-8u161-linux-x64.rpm && \
yum localinstall -y jre-8u161-linux-x64.rpm && \
rm -rf jre-8u161-linux-x64.rpm && \
yum install -y net-tools && \
yum install -y graphviz && \
rm -rf /var/cache/yum

# Set environment variables.
ENV JAVA_HOME /usr/java/jre1.8.0_161
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["bash"]
