#!/bin/bash
#
# securityBroker      Startup script for the Open Security Controller
#
# chkconfig: - 85 15
# description: The Open Security Controller is the broker server for the
#              vmiDC service
# processname: java
# config: /opt/vmidc/bin/vmidcServer.conf 
#
### BEGIN INIT INFO
# Provides: vmidc
# Required-Start: $local_fs $remote_fs $network $named
# Required-Stop: $local_fs $remote_fs $network
# Short-Description: start and stop vmidcServer
### END INIT INFO

# Source function library
. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/sercurityBroker ]; then
  . /etc/sysconfig/sercurityBroker
fi

start() {
  if [ ! -f /mnt/media/ovf-env.xml ]; then
    [ -d /mnt/media ] || /bin/mkdir /mnt/media
    action $"Mounting CDROM" /bin/mount /dev/cdrom /mnt/media
  fi

  cd /opt/vmidc/bin
  action $"Starting Open Security Controller Server" ./vmidc.sh --start
}

stop() {
  cd /opt/vmidc/bin
  action $"Stopping Open Security Controller Server" ./vmidc.sh --stop
}

status() {
  cd /opt/vmidc/bin
  ./vmidc.sh --status
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo $"Usage: securityBroker {start|stop|restart|status}"
    ;;
esac

exit 0
