#!/bin/bash
protected_branch='master'
# check each branch being pushed
while read local_ref local_sha remote_ref remote_sha
do
remote_branch=$(echo $remote_ref | sed -e 's,.*/\(.*\),\1,')
if [ $protected_branch = $remote_branch ]
then 
echo "ABORT PUSH: Not allowed to push directly to $protected_branch. Use --no-verify to force."
exit 1 # push will not execute
fi
done
